owner: chanderinguva
repo: upptime

sites:
  - name: Airflow
    url: https://airflow.inguva.dev
  - name: Okta Login
    url: https://login.inguva.dev
  - name: Blog
    url: https://blog.inguva.dev
  - name: Jira
    url: https://inguva-dev.atlassian.net
  - name: SCIM Server
    url: https://airflow.inguva.dev/scim/v2/ServiceProviderConfig

assignees:
  - chanderinguva

status-website:
  cname: status.inguva.dev
  name: Inguva Dev Status
  description: Real-time status of all inguva.dev services
  theme: dark
  navbar:
    - title: Blog
      href: https://blog.inguva.dev
    - title: Airflow
      href: https://airflow.inguva.dev

notifications:
  - type: slack
    webhook: ${{ secrets.SLACK_WEBHOOK }}
